DROP TABLE IF EXISTS Usraccount CASCADE;
DROP TABLE IF EXISTS Drink CASCADE;
DROP TYPE IF EXISTS amount_type CASCADE;
DROP TABLE IF EXISTS Ingredient CASCADE;
DROP TABLE IF EXISTS Preparation CASCADE;
DROP TABLE IF EXISTS Followed CASCADE;

